name: iBoot64Patcher

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 1 *'
    - cron: '0 0 1 4 *'
    - cron: '0 0 30 6 *'
    - cron: '0 0 28 9 *'
    - cron: '0 0 27 12 *'

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'
          fetch-depth: 0
      - name: Linux Build
        id: Linux
        uses: addnab/docker-run-action@v3
        with:
          image: debian:buster-slim
          options: -v ${{ github.workspace }}/..:/tmp/Builder/repos/
          run: |
            /tmp/Builder/repos/iBoot64Patcher/.github/workflows/linux-bootstrap.sh
            /tmp/Builder/repos/iBoot64Patcher/.github/workflows/linux-build.sh
            /tmp/Builder/repos/iBoot64Patcher/.github/workflows/linux-post.sh
      - name: Linux x86_64 RELEASE Build
        run: |
          mkdir -p /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/
          docker cp $(docker ps -ql):/tmp/Builder/repos/iBoot64Patcher/.github/workflows/name1.txt /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/
          docker cp $(docker ps -ql):/tmp/Builder/repos/iBoot64Patcher/.github/workflows/iBoot64Patcher1.tar.xz /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/
          mv /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/iBoot64Patcher1.tar.xz /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/$(cat /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/name1.txt)
      - name: Linux x86_64 DEBUG Build
        run: |
          mkdir -p /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/
          docker cp $(docker ps -ql):/tmp/Builder/repos/iBoot64Patcher/.github/workflows/name2.txt /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/
          docker cp $(docker ps -ql):/tmp/Builder/repos/iBoot64Patcher/.github/workflows/iBoot64Patcher2.tar.xz /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/
          mv /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/iBoot64Patcher2.tar.xz /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/$(cat /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/name2.txt)
      - name: iBoot64Patcher Linux x86_64 RELEASE Archive
        id: iBoot64Patcher-Linux-x86_64-RELEASE-Archive
        uses: actions/upload-artifact@v4
        with:
          name: iBoot64Patcher-Linux-x86_64-RELEASE
          path: /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/iBoot64Patcher-Linux-x86_64*-RELEASE.tar.xz
      - name: iBoot64Patcher Linux x86_64 DEBUG Archive
        id: iBoot64Patcher-Linux-x86_64-DEBUG-Archive
        uses: actions/upload-artifact@v4
        with:
          name: iBoot64Patcher-Linux-x86_64-DEBUG
          path: /home/runner/work/iBoot64Patcher/iBoot64Patcher/.github/workflows/iBoot64Patcher-Linux-x86_64*-DEBUG.tar.xz
